using System.Diagnostics.Metrics;

namespace SOCPlatform.Infrastructure.Observability;

/// <summary>
/// Custom <see cref="Meter"/> + instruments for SentinelOps. Exposed under the
/// <c>socplatform</c> meter name so OpenTelemetry can subscribe with
/// <c>builder.AddMeter(SocMetrics.MeterName)</c>.
///
/// Prometheus naming convention: <c>socp_*</c> snake_case per
/// https://prometheus.io/docs/practices/naming/. Registered as a singleton
/// so every component shares the same instruments.
///
/// Instruments
/// -----------
///   • alerts_total               Counter&lt;long&gt;   tags: severity, rule
///   • sla_breaches_total         Counter&lt;long&gt;   tags: severity
///   • detection_duration         Histogram&lt;double&gt; (ms) tags: rule
///   • ingestion_logs_total       Counter&lt;long&gt;   tags: source, severity
///   • ml_inference_duration      Histogram&lt;double&gt; (ms) tags: model
/// </summary>
public sealed class SocMetrics : IDisposable
{
    public const string MeterName = "socplatform";
    public const string MeterVersion = "1.0.0";

    private readonly Meter _meter;

    public Counter<long>      AlertsTotal             { get; }
    public Counter<long>      SlaBreachesTotal        { get; }
    public Histogram<double>  DetectionDurationMs     { get; }
    public Counter<long>      IngestionLogsTotal      { get; }
    public Histogram<double>  MlInferenceDurationMs   { get; }

    public SocMetrics(IMeterFactory meterFactory)
    {
        _meter = meterFactory.Create(MeterName, MeterVersion);

        AlertsTotal = _meter.CreateCounter<long>(
            "socp_alerts_total",
            unit: "alerts",
            description: "Alerts generated by the detection engine, tagged by severity and rule");

        SlaBreachesTotal = _meter.CreateCounter<long>(
            "socp_sla_breaches_total",
            unit: "alerts",
            description: "Alerts whose SLA deadline passed without resolution");

        DetectionDurationMs = _meter.CreateHistogram<double>(
            "socp_detection_duration_ms",
            unit: "ms",
            description: "Time spent evaluating one detection rule over one batch of events");

        IngestionLogsTotal = _meter.CreateCounter<long>(
            "socp_ingestion_logs_total",
            unit: "logs",
            description: "Logs accepted by the ingestion endpoint");

        MlInferenceDurationMs = _meter.CreateHistogram<double>(
            "socp_ml_inference_duration_ms",
            unit: "ms",
            description: "Round-trip latency to the Python ML microservice, tagged by model");
    }

    public void Dispose() => _meter.Dispose();
}
