using SOCPlatform.Core.Entities;

namespace SOCPlatform.Detection.Rules;

/// <summary>
/// Interface for all detection rules.
/// Each rule evaluates a batch of security events and produces alerts.
/// </summary>
public interface IDetectionRule
{
    /// <summary>Rule display name.</summary>
    string Name { get; }

    /// <summary>MITRE ATT&CK technique ID (e.g., T1110).</summary>
    string MitreTechnique { get; }

    /// <summary>MITRE ATT&CK tactic (e.g., Credential Access).</summary>
    string MitreTactic { get; }

    /// <summary>Default severity for alerts generated by this rule.</summary>
    string Severity { get; }

    /// <summary>Whether this rule is currently enabled.</summary>
    bool IsEnabled { get; set; }

    /// <summary>
    /// Evaluate a batch of recent security events and return any alerts that should be raised.
    /// </summary>
    Task<List<Alert>> EvaluateAsync(List<SecurityEvent> events, CancellationToken ct = default);
}
