using SOCPlatform.Core.Enums;

namespace SOCPlatform.Core.Entities;

/// <summary>
/// Represents a security alert generated by the detection engine.
/// Follows SOC lifecycle: NEW → IN_PROGRESS → ESCALATED → RESOLVED → CLOSED
/// </summary>
public class Alert
{
    public Guid Id { get; set; }
    public long? EventId { get; set; }
    public Guid? AssignedTo { get; set; }
    public Guid? IncidentId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public Severity Severity { get; set; }
    public AlertStatus Status { get; set; } = AlertStatus.New;
    public string? DetectionRuleName { get; set; }
    public Guid? DetectionRuleId { get; set; }
    public string? MitreTechnique { get; set; }
    public string? MitreTactic { get; set; }
    public string? AffectedUser { get; set; }
    public string? AffectedDevice { get; set; }
    public string? SourceIP { get; set; }
    public string? RecommendedAction { get; set; }
    public DateTime? SlaDeadline { get; set; }
    public DateTime CreatedAt { get; set; } = DateTime.UtcNow;
    public DateTime? AcknowledgedAt { get; set; }
    public DateTime? ResolvedAt { get; set; }
    public DateTime? ClosedAt { get; set; }
    public DateTime UpdatedAt { get; set; } = DateTime.UtcNow;

    // Navigation
    public SecurityEvent? Event { get; set; }
    public User? AssignedAnalyst { get; set; }
    public Incident? Incident { get; set; }
    public DetectionRule? DetectionRule { get; set; }
    public ICollection<PlaybookExecution> PlaybookExecutions { get; set; } = new List<PlaybookExecution>();
}
